export interface CompanyInfo {
    companyName: string,
    companyEmail: string,
    companyEmail2: string,
    companyBOxNumber: number,
    companyCountryLoaction: string,
    companyRegionLoaction: string,
    companyCityLoaction: string,
    companyPlotNumber: number,
    companyStreetName: string,
    companyBuilding: string,
    companyOfficeFloor: string,
    companyPhoneContact1: number,
    companyPhoneContact2: number,
  }